language: elixir
git:
  depth: 1000
cache:
  directories:
    - _build
    - deps
services:
  - docker
  - redis-server
  - rabbitmq
addons:
  apt:
    update: true
    packages:
      - docker-ce
elixir:
  - 1.6.5
otp_release:
  - 20.3.6
notifications:
  slack:
    rooms:
      - secure: "gsGwHnxV7k/MoNGG/J2N5DJ8WxMkQLoCMWdUQ7TdPN7GQnjuSNoQ7dQQZCvfE01gD5pkg8JH4yQW8vcOFQqmnNfSknrxh8kRCC7nugxwei93F3uyHzTBSL4gHbWb3ThxPXCJ3pMfD/jt2oodH2KdqCotWJSLQSq+asVmSloPUkuRNEqXO+jPzoToSCb+PCwUeeDQXv0buZYSYEAkSoXCJp8q8O8Mzb7NWlc+R0x8ehFWA5xYr6gnahXxdWYjLUdJ7GH0HmdH6q7y+NXiSSkRJ8XQCO0/Eb9PtHl51gf6GpmZgMm/UrlKQ2H48C0gIbv5YMFeQqmQbxtUpqq2YGzo2dMxugEsct/wzTn6K5571HLm0KmfSTpMvVfGHU4p+17jj/dRYkQjB45+1CeWyn4MQYv7L7zaqsFWHpkOZO6xtwrfu0/kk4ZVZ3zxHdhDhzjuEQFUIPr0GqYsgVeIzkWq75EEh96G33om364jio8p86HPkNLLKQzrvNa20ElgJvMvxCy0AR0Md/9f7+X14gqC2LQe7umXcOE7nSmnDWQITGIl9MnNJgnazmksboSipswLH6rVg2os4TXZRXqfo2SPMHZrfn4ImE89pdvVB80E/kUhPeyq/ztPnUvIZlaIoBkfeZnwlk0YUH+pilM/QN78GV3/kixHIqxGDDR2mBQaO88="
    on_success: always
env:
  global:
    - Chart=kimlic-core
    - MIX_ENV=test
    - REQUIRE_VERSION_TAGS="true"
    - DOCKER_HUB_ACCOUNT=kimlictr
    - TRUNK_BRANCH="docker"
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose RabbitMQ to Docker container
  - sudo ./bin/ci/init-rabbitmq.sh
before_script:
  # Create test user for rabbitMQ
#  - rabbitmqctl add_user test test
#  - rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
  # Extract project name and version from mix.exs
  - source ./bin/ci/rel/fetch-project-environment.sh
  # Load information about new version
  - source ./bin/ci/release/fetch-source-version.sh
script:
  # Check for versioning error
  - ./bin/ci/release/check-version-error.sh || travis_terminate 1
  # Increment version in mix.exs
  - ./bin/ci/release/put-source-version.sh || travis_terminate 1
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
  # Build Docker container
  - ./bin/ci/rel/build-container.sh || travis_terminate 1
  # Run Docker container
  - sudo ./bin/ci/rel/start-container.sh
  # Check that Docker container started
  - sudo ./bin/ci/release/check-container.sh || travis_terminate 1
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/rel/push-changes.sh || travis_terminate 1
#  - echo "Decrypting deploy key..."
#  - openssl aes-256-cbc -K $encrypted_c996ec964e08_key -iv $encrypted_c996ec964e08_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
#  - sudo ./bin/deploy.sh || travis_terminate 1
